for d in ./*/*/ ; do (cd "$d" && rm 2011Census_B04A*); done 
for d in ./*/*/ ; do (cd "$d" && rm 2011Census_B04B*); done 
for d in ./*/*/ ; do (cd "$d" && rm 2011Census_B08A*); done 
for d in ./*/*/ ; do (cd "$d" && rm 2011Census_B08B*); done 
for d in ./*/*/ ; do (cd "$d" && rm 2011Census_B10A*); done 
for d in ./*/*/ ; do (cd "$d" && rm 2011Census_B10B*); done 
for d in ./*/*/ ; do (cd "$d" && rm 2011Census_B10C*); done 
for d in ./*/*/ ; do (cd "$d" && rm 2011Census_B11A*); done 
for d in ./*/*/ ; do (cd "$d" && rm 2011Census_B11B*); done 
for d in ./*/*/ ; do (cd "$d" && rm 2011Census_B12A*); done 
for d in ./*/*/ ; do (cd "$d" && rm 2011Census_B12B*); done 
for d in ./*/*/ ; do (cd "$d" && rm 2011Census_B16A*); done 
for d in ./*/*/ ; do (cd "$d" && rm 2011Census_B16B*); done 
for d in ./*/*/ ; do (cd "$d" && rm 2011Census_B17A*); done 
for d in ./*/*/ ; do (cd "$d" && rm 2011Census_B17B*); done 
for d in ./*/*/ ; do (cd "$d" && rm 2011Census_B20A*); done 
for d in ./*/*/ ; do (cd "$d" && rm 2011Census_B20B*); done 
for d in ./*/*/ ; do (cd "$d" && rm 2011Census_B22A*); done 
for d in ./*/*/ ; do (cd "$d" && rm 2011Census_B22B*); done 
for d in ./*/*/ ; do (cd "$d" && rm 2011Census_B23A*); done 
for d in ./*/*/ ; do (cd "$d" && rm 2011Census_B23B*); done 
for d in ./*/*/ ; do (cd "$d" && rm 2011Census_B40A*); done 
for d in ./*/*/ ; do (cd "$d" && rm 2011Census_B40B*); done 
for d in ./*/*/ ; do (cd "$d" && rm 2011Census_B41A*); done 
for d in ./*/*/ ; do (cd "$d" && rm 2011Census_B41B*); done 
for d in ./*/*/ ; do (cd "$d" && rm 2011Census_B41C*); done 
for d in ./*/*/ ; do (cd "$d" && rm 2011Census_B42A*); done 
for d in ./*/*/ ; do (cd "$d" && rm 2011Census_B42B*); done 
for d in ./*/*/ ; do (cd "$d" && rm 2011Census_B43A*); done 
for d in ./*/*/ ; do (cd "$d" && rm 2011Census_B43B*); done 
for d in ./*/*/ ; do (cd "$d" && rm 2011Census_B43C*); done 
for d in ./*/*/ ; do (cd "$d" && rm 2011Census_B43D*); done 
for d in ./*/*/ ; do (cd "$d" && rm 2011Census_B44A*); done 
for d in ./*/*/ ; do (cd "$d" && rm 2011Census_B44B*); done 
for d in ./*/*/ ; do (cd "$d" && rm 2011Census_B45A*); done 
for d in ./*/*/ ; do (cd "$d" && rm 2011Census_B45B*); done 

